# Ce fichier est automatiquement appliqué en complément de docker-compose.yml. Il est local à ton environnement de développement et ne sera pas utilisé par l’agence (sauf si elle le souhaite explicitement).
#
# ✅ Objectifs pour le développement local :
# Monter les fichiers de l'hôte (Mac) dans le conteneur pour:
# Editer le code, les scripts, les données, etc.,
# Et que le conteneur voit ces changements immédiatement.
# Ajouter éventuellement des outils supplémentaires (ex: volume de logs...).

# ✅ Explication des volumes :
#Volume	                  → But
#./src:/app/src	          → Monte le code source
#./config:/app/config	  → Monte la config (config.py, .env...)
#./scripts:/app/scripts	  → Pour utiliser les outils comme generate_tree.py
#./docs:/app/docs	      → Pour documenter et vérifier visuellement
#./src/data:/app/src/data → Monte les données en lecture/écriture






services:
  # --- App (Dash) ---
  obyia-app:
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./scripts:/app/scripts
      - ./assets:/app/assets
      - ./outputs:/app/outputs
      - ./src/data:/app/src/data
    env_file:
      - .env
    environment:
      - ENV=dev
    # Paramétrage des ports et command -> hérités du compose de base

  # --- API (Uvicorn) ---
  obyia-api:
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./scripts:/app/scripts
      - ./src/data:/app/src/data
      - ./outputs:/app/outputs
      # Monte les assets si l'API en sert (sinon commente la ligne suivante)
      - ./assets:/app/assets
    env_file:
      - .env
    environment:
      - ENV=dev
    # Profils/ports/command restent ceux du fichier principal

  # --- Doc (MkDocs) ---
  obyia-doc:
    volumes:
      - ./docs:/app/docs
      # Monte les assets si la doc les référence (images, logos…)
      - ./assets:/app/assets
      # Si mkdocs.yml est à la racine du repo (et non dans /docs),
      # décommenter la ligne suivante pour le hot-reload :
      - ./mkdocs.yml:/app/mkdocs.yml
    env_file:
      - .env
    environment:
      - ENV=dev
    # Ports/command/profil hérités du compose de base

